name: "run"
on:
  pull_request:
  push:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v25
      with:
        github_access_token: ${{ secrets.GITHUB_TOKEN }}
    - run: nix run --refresh "github:maxhbr/myphoto"#myphoto-stack -- --workdir=workdir *.JPG
    - run: ls
    - run: ls workdir
    - uses: actions/upload-artifact@v4
      with:
        name: output
        path: workdir/*.png
